/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-background": "#e1e2eb",
        "on-error": "#690005",
        "on-secondary": "#003910",
        "on-primary-fixed-variant": "#00468d",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#7200a3",
        "tertiary-fixed-dim": "#e9b3ff",
        "surface": "#10131a",
        "secondary-fixed": "#6cff82",
        "surface-variant": "#32353c",
        "primary": "#aac7ff",
        "surface-container-high": "#272a31",
        "secondary-container": "#09bf49",
        "surface-dim": "#10131a",
        "on-tertiary-fixed": "#310048",
        "inverse-primary": "#005db8",
        "on-primary": "#003064",
        "tertiary-fixed": "#f6d9ff",
        "surface-container-highest": "#32353c",
        "primary-container": "#3e90ff",
        "on-tertiary": "#510074",
        "surface-bright": "#363940",
        "on-secondary-fixed-variant": "#00531a",
        "tertiary": "#e9b3ff",
        "on-secondary-container": "#004615",
        "surface-container-lowest": "#0b0e14",
        "secondary-fixed-dim": "#47e266",
        "on-surface": "#e1e2eb",
        "on-tertiary-container": "#460066",
        "on-secondary-fixed": "#002106",
        "on-primary-fixed": "#001b3e",
        "tertiary-container": "#c863fb",
        "outline": "#8b91a0",
        "surface-container-low": "#191c22",
        "primary-fixed-dim": "#aac7ff",
        "inverse-surface": "#e1e2eb",
        "inverse-on-surface": "#2e3037",
        "on-surface-variant": "#c0c6d6",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "secondary": "#47e266",
        "outline-variant": "#414754",
        "on-primary-container": "#002957",
        "background": "#10131a",
        "surface-tint": "#aac7ff",
        "primary-fixed": "#d6e3ff",
        "surface-container": "#1d2026",
        banco: {
          popular: '#003882',
          bhd: '#008752',
          promerica: '#00965E',
          qik: '#6C2BD9'
        }
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "margin": "2.5rem",
        "gutter-mobile": "0.75rem",
        "gutter": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "space-xl": "2.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "mono-metric": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-metric": ["15px", { lineHeight: "20px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["17px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "13px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
